teams_display:
    path:     /display_teams/{pageIndex}
    defaults:
        _controller: "QuidditchBundle:Team:teamsDisplay"
        pageIndex: 1
    methods:  [GET, POST]

team_autocreate:
    path:     /autocreate
    defaults: { _controller: "QuidditchBundle:Team:autocreate" }
    methods:  GET

team_index:
    path:     /
    defaults: { _controller: "QuidditchBundle:Team:index" }
    methods:  GET

team_show:
    path:     /{id}/show
    defaults: { _controller: "QuidditchBundle:Team:show" }
    methods:  GET

team_new:
    path:     /new
    defaults: { _controller: "QuidditchBundle:Team:new" }
    methods:  [GET, POST]

team_edit:
    path:     /{id}/edit
    defaults: { _controller: "QuidditchBundle:Team:edit" }
    methods:  [GET, POST]

team_delete:
    path:     /{id}/delete
    defaults: { _controller: "QuidditchBundle:Team:delete" }
    methods:  DELETE
