<?php

namespace QuidditchBundle\Repository;

use QuidditchBundle\Controller\TeamController;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByPage($page) {
		$qb = $this->createQueryBuilder('p')
			->setFirstResult(max(0, $page - 1) * TeamController::ITEMS_PER_PAGE)
			->setMaxResults(TeamController::ITEMS_PER_PAGE)
		;
		return $qb->getQuery()->getResult();
	}
}
