QuidditchBundle\Entity\Team:
    type: entity
    table: null
    repositoryClass: QuidditchBundle\Repository\TeamRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        country:
            type: string
            length: 255
        creationDate:
            type: datetime
    oneToMany:
        players:
            targetEntity: Player
            cascade: ['persist']
            mappedBy: team
        wonGames:
            targetEntity: Game
            mappedBy: winner

    manyToMany:
        playedGames:
          targetEntity: Game
          mappedBy: teams
    lifecycleCallbacks:
        prePersist: [setCreationDateNow]
